name: 'deploy-resources'

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'test-branch'
env:
  rg_name: 'git2-rg'
  location: 'eastus'
  
jobs:
   create_resources:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3.3.0
         
       - name: Log in to Azure with SP
         uses: Azure/login@v1.4.6
         with:
           creds: ${{secret.AZURE_CREDENTIAL}}
           
       - run: |
           az group create -l ${{env.location}} -g ${{env.rg_name}}
   
       - name: Deploy Azure Resource Manager (ARM) Template
         uses: Azure/arm-deploy@v1.0.9
         with:
           resourceGroupName: ${{env.rg_name}}
           template: ./templates/azure_deploy.json
           parameters: ./templates/azure_deploy_param.json
     
