name: 'deploy-resources'

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'test-branch'
env:
  rg_name: 'git2-rg'
  location: 'eastus'
  
jobs:
   create_resource_group:
     runs-on: ubuntu-latest
     steps:
       - name: 'Log in to Azure with SP'
         uses: Azure/login@v1.4.6
         with:
           creds: ${{secret.AZURE_CREDENTIAL}}
           
       - run: |
           az group create -l ${{env.location}} -g ${{env.rg_name}}
   deploy_arm_template:
  
